### ISSUE TITLE
 Problems with QuoteSource.get_source('Yahoo')

### ISSUE THREAD

**Issue by danigarod** [dodid/minitrade#5]
Hi, I am trying to use the QuantSource method to retrieve data from Yahoo, but I am getting this error. Do you have any idea of the problem?

Exception has occurred: ImportError
cannot import name 'config' from 'minitrade.utils.config' (C:\Users\garcd3\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\minitrade\utils\config.py)
File "C:\Users\garcd3\Trade\Old\Minitrade.py", line 93, in
yahoo = QuoteSource,get_source('Yahoo')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'config' from 'minitrade.utils.config' (C:\Users\garcd3\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\minitrade\utils\config.py)

**Comment by dodid** [comment]
I have never tested Minitrade on Windows, but try `minitrade init` and see if that fixes your problem?

**Comment by dodid** [comment]
This should have been fixed in v0.1.39. Make sure you run `minitrade init` to set up the config before use.
